<?php

namespace CMS\BlogBundle\Repository;


/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Method to get the comment's article
     *
     * @param $articleId
     * @return array
     */
    public function getCommentForArticle($articleId)
    {

        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.article = :article_id')
            ->addOrderBy('c.publishedAt')
            ->setParameter('article_id', $articleId);

        return $qb->getQuery()
            ->getResult();
    }
}
