_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error

_main:
    resource: routing.yml

# page de test translation
cms_blog_translation:
    path: /{_locale}/traduction/{name}
    defaults:
        _controller: CMSBlogBundle:Article:translation

# Page de teste json ParamConverter
cms_blog_paramconverter:
    path: /test/{json}
    defaults:
     _controller: "CMSBlogBundle:Article:ParamConverter"

# route de la console intégrée
coresphere_console:
    resource: .
    type: extra
