cms_article:
    resource: "@CMSBlogBundle/Resources/config/routing_inc/routing_article.yml"

cms_user:
    resource: "@CMSBlogBundle/Resources/config/routing_inc/routing_user.yml"

cms_category:
    resource: "@CMSBlogBundle/Resources/config/routing_inc/routing_category.yml"

cms_menu:
    resource: "@CMSBlogBundle/Resources/config/routing_inc/routing_menu.yml"

cms_contact:
    resource: "@CMSBlogBundle/Resources/config/routing_inc/routing_contact.yml"

cms_custom:
    resource: "@CMSBlogBundle/Resources/config/routing_inc/routing_custom.yml"


# Commentaire
cms_comment_delete:
    path: article/comment/delete/{id}
    defaults:
        _controller: CMSBlogBundle:Comment:delete







