cms_blog_home:
    path: /{page}
    defaults:
        _controller: CMSBlogBundle:Article:index
        page: 1
    requirements:
        page: \d*

cms_blog_fiche:
    path: /article/{id}
    defaults:
        _controller: CMSBlogBundle:Article:fiche

    requirements:
        id: \d+

cms_blog_add:
    path: /article/add
    defaults:
        _controller: CMSBlogBundle:Article:add

cms_blog_edit:
    path: /article/edit/{id}
    defaults:
        _controller: CMSBlogBundle:Article:edit
    requirements:
        id: \d+

cms_blog_delete:
    path: /article/delete/{id}
    defaults:
        _controller: CMSBlogBundle:Article:delete

cms_user_list:
    path: /list
    defaults:
        _controller: CMSBlogBundle:User:list

cms_user_fiche:
    path: /fiche/{id}
    defaults:
        _controller: CMSBlogBundle:User:fiche
    requirements:
        id: \d+

cms_user_del:
    path:    /fiche/delete/{id}
    defaults: { _controller: CMSBlogBundle:User:deleteUser, id: 0}

cms_user_edit:
    path: /fiche/edit/{id}
    defaults:
        _controller: CMSBlogBundle:User:updateUserRole
    requirements:
        id: \d+

cms_compte_index:
    path: /compte/index/{id}
    defaults:
        _controller: CMSBlogBundle:Compte:index
    requirements:
        id: \d+

cms_category_list:
    path: /category/list
    defaults:
        _controller: CMSBlogBundle:Category:list

cms_category_add:
    path: /category/add
    defaults:
        _controller: CMSBlogBundle:Category:add

cms_category_delete:
    path: /category/delete/{id}
    defaults:
        _controller: CMSBlogBundle:Category:delete

cms_menu_index:
    path: /menu/index
    defaults:
        _controller: CMSBlogBundle:Menu:index

cms_menu_add:
    path: /menu/addname
    defaults:
        _controller: CMSBlogBundle:Menu:addName

cms_menu_listcate:
    path: /menu/listcate/{id}
    defaults:
        _controller: CMSBlogBundle:Menu:listCateByMenu