services:
#    cms_blog.example:
#        class: CMS\BlogBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

# Service Antispam
    cms_blog.antispam:
        class: CMS\BlogBundle\Antispam\BlogAntispam
        arguments:
         - "@mailer"
         - 50
        calls:
         - [ setLocale, [%locale%]]

#AntifloodValidator
    cms_blog.validator.antiflood:
        class: CMS\BlogBundle\Validator\AntifloodValidator
        arguments: ["@request_stack", "@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: cms_blog_antiflood}

# Service Beta Listener d'événement
    cms_blog.beta.html_adder:
        class: CMS\BlogBundle\Beta\BetaHTMLAdder
# Service Beta Listener suite
    cms_blog.beta.listener:
        class: CMS\BlogBundle\Beta\BetaListener
        arguments:
         - "@cms_blog.beta.html_adder"
         - "2017-03-24"
        tags:
         - { name: kernel.event_listener, event: kernel.response, method: processBeta }

# Service Twig spam Extension

    cms_blog.twig.antispam_extension:
        class: CMS\BlogBundle\Twig\AntispamExtension
        arguments:
         - "@cms_blog.antispam"
        tags:
         - {name: twig.extension }