cms_menu_index:
    path: /menu/index
    defaults:
        _controller: CMSBlogBundle:Menu:index

cms_menu_add:
    path: /menu/addname
    defaults:
        _controller: CMSBlogBundle:Menu:addName

cms_menu_listcate:
    path: /menu/listcate/{id}
    defaults:
        _controller: CMSBlogBundle:Menu:listCateByMenu

cms_menu_show_article:
    path: /menu/show/article/{id}
    defaults:
        _controller: CMSBlogBundle:Menu:showArticleByMenu

cms_menu_delete:
    path: /menu/delete/{id}
    defaults:
        _controller: CMSBlogBundle:Menu:deleteMenu

cms_menu_edit:
    path: /menu/edit/{id}
    defaults:
        _controller: CMSBlogBundle:Menu:edit