CMS\UserBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: CMS\UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        age:
            type: integer
            nullable: true
        city:
            type: string
            nullable: true
        url:
            type: string
            nullable: true
        dateInscription:
            type: datetime
            nullable: true
    oneToOne:
        avatar:
            targetEntity: CMS\BlogBundle\Entity\Avatar
            joinColumn:
                name: avatar_id
                referencedColumnName: id
                onDelete: CASCADE
            cascade: ["persist", "merge"]

    lifecycleCallbacks: {  }
